baseURL: "https://matimacazaga.github.io/"
languageCode: en-us
title: MM
paginate: 5
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: About
                  url: about/
                  weight: 10
                # - name: WiKi
                #   url: https://github.com/adityatelange/hugo-PaperMod/wiki/
                # - name: Discord
                #   url: https://discord.gg/ahpmTvhVmp

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Personal Blog"
    author: "Matias Macazaga"
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]
    hideSummary: true

    # profileMode:
    #     enabled: false
    #     title: PaperMod
    #     imageUrl: "#"
    #     imageTitle: my image
    #     # imageWidth: 120
    #     # imageHeight: 120
    #     buttons:
    #         - name: Archives
    #           url: archives
    #         - name: Tags
    #           url: tags

    # homeInfoParams:
    #     Title: "A quant's journey"
    #     Content: >
    #         Welcome to my personal blog! My name is Matias Macazaga 
    #         and I'm from Argentina. I'm a Quantitative Developer / Data Scientist 
    #         with experience in Machine Learning models validation, development and 
    #         deployment, Portfolio Management and Optimization, and Risk Management.
            
    #         Feel free to contact me at mdmacazaga@gmail.com or by [LinkedIn](linkedin.com/in/matias-macazaga).
    
    socialIcons:
        - name: github
          url: "https://github.com/matimacazaga"
        - name: linkedin
          url: linkedin.com/in/matias-macazaga

    # editPost:
    #     URL: "https://github.com/matimacazaga/matimacazaga.github.io/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
        favicon: "/favicon/favicon.ico"
        favicon16x16: "/favicon/favicon-16x16.png"
        favicon32x32: "/favicon/favicon-32x32.png"
        apple_touch_icon: "/favicon/apple-touch-icon.png"
        safari_pinned_tab: "/favicon/safari-pinned-tab.svg"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # style: dracula

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
